INSERT INTO THE_FOREIGN_FOUR.Usuarios (user_name,password,nombre,apellido,tipo_doc,nro_doc,mail,telefono,direccion,fecha_nac,baja_logica,estado)
VALUES ('admin','w23e','Administrador general',null,'DNI',324783627,'admn@hotmail.com',34534545,Null,GETDATE(),'N','H')

--NO CREO MAS USUARIOS YA QUE CON ESTE USUARIO PODES CREAR A LOS OTROS DESDE EL ABM DE USUARIO

INSERT INTO THE_FOREIGN_FOUR.Roles (nombre,estado)
VALUES ('Administrador','H')
INSERT INTO THE_FOREIGN_FOUR.Roles (nombre,estado)
VALUES ('Recepcionista','H')
INSERT INTO THE_FOREIGN_FOUR.Roles (nombre,estado)
VALUES ('Guest','H')
INSERT INTO THE_FOREIGN_FOUR.Roles (nombre,estado)
VALUES ('Administrador General','H')

insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('ABM Usuario')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('ABM Clientes')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('ABM Hotel')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('ABM Habitacion')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('ABM Regimen De Estadia')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('Generar o Modificar Reserva')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('Cancelar Reserva')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('Registrar Estadia')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('Registrar Consumibles')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('Facturar Estadia')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('Listado Estadistico')
insert into THE_FOREIGN_FOUR.Funcionalidades (nombre) 
values ('ABM Rol')

--OJO DE ACA EN ADELANTE DEPENDE DE COMO LES DE EL CODIGO DE USUARIO CUANDO HALLAN HECHO EL INSERT
--Y TAMBIEN LOS DIFERENTES CODIGOS DE HOTELES(yo tengo que el codigo de hotel va de 1 a 16)
--Y TAMBIEN DE LOS DIFERENTES CODIGOS DE FUNCIONALIDADES
--POR CADA INSERT EN LA TABLA UsuariosPorHotel poner en value por ejemplo el primero 
--que es (1,1,4) poner (codigo de usuario que les genero cuando insertaron el usuario,el cod del primer hotel, el codigo del rol Administrador General)
--y asi con susecivamente todos los inserts
--es una cagada desp hay que cambiarlo

INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,1,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,2,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,3,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,4,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,5,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,6,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,7,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,8,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,9,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,10,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,11,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,12,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,13,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,14,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,15,4)
INSERT INTO THE_FOREIGN_FOUR.UsuariosPorHotel (cod_usuario,cod_hotel,cod_rol)
VALUES (1,16,4)

--ACA LO MISMO PERO CON LAS DISTINTAS FUNCIONALIDADES Y EL COD DEL ROL Administrador General

INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (1,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (2,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (3,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (4,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (5,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (6,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (7,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (8,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (9,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (10,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (11,4)
INSERT INTO THE_FOREIGN_FOUR.FuncionalidadPorRol (cod_funcion,cod_rol)
VALUES (12,4)

--NOTA: CREAR TODAS LAS VISTAS DE Script-ui ya que cree algunas para facilitar el acceso a los datos 
--seguramente si rompe en algun lado es por que falta alguna vista